# Generated by Django 4.0.6 on 2023-01-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='branch',
        ),
    ]
