# Generated by Django 4.0.6 on 2023-01-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_kh', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'ftb_branch',
            },
        ),
    ]
