# Generated by Django 4.0.6 on 2023-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmodel',
            name='address_en',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branchmodel',
            name='address_kh',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branchmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='code',
            field=models.CharField(max_length=9),
        ),
    ]
