# Generated by Django 4.0.6 on 2023-01-02 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_user_ip_address_user_pc_id_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 6, 54, 59, 495428)),
        ),
    ]
